# Generated by Django 3.0 on 2020-11-30 01:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCamera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Câmera: ')),
                ('numeroCamera', models.IntegerField(blank=True, null=True, verbose_name='Número Câmera: ')),
                ('numeroIp', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP Câmera: ')),
                ('fabricanteCamera', models.CharField(choices=[('Axis', 'Axis'), ('Interlbras', 'Intelbras')], max_length=255)),
                ('loginCamera', models.CharField(blank=True, max_length=20, null=True, verbose_name='Login: ')),
                ('senhaCamera', models.CharField(blank=True, max_length=20, null=True, verbose_name='Senha: ')),
                ('equipamentoGravacao', models.CharField(choices=[('DVR 1', 'DVR 1'), ('DVR 2', 'DVR 2'), ('DVR 3', 'DVR 3'), ('NVR 1', 'NVR 1'), ('NVR 2', 'NVR 2'), ('NVR 3', 'NVR 3'), ('VAU 1', 'VAU 1'), ('VAU 2', 'VAU 2'), ('VAU 3', 'VAU 3')], max_length=50, verbose_name='Equipamento de Gravação: ')),
            ],
            options={
                'verbose_name_plural': 'Câmeras IP',
                'db_table': 'tbCameraIp',
            },
        ),
        migrations.CreateModel(
            name='Gerenciadoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerenciadora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gerenciadora: ')),
                ('statusGerenciadora', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50, verbose_name='Status:')),
            ],
            options={
                'verbose_name_plural': 'Gerenciadoras',
                'db_table': 'tbGerenciadoras',
            },
        ),
        migrations.CreateModel(
            name='Sap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadroSap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quadros Automação: ')),
                ('statusSap', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50, verbose_name='Status')),
                ('quantidadeControladoras', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Controladoras: ')),
                ('localizazao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização: ')),
                ('observacoesSap', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quadros SCIRP',
                'db_table': 'tbSap',
            },
        ),
    ]
