# Generated by Django 3.0 on 2020-12-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sap',
            name='Gerenciadora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programa.Gerenciadoras'),
            preserve_default=False,
        ),
    ]
