# Generated by Django 3.0 on 2020-12-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_sap_gerenciadora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sap',
            old_name='localizazao',
            new_name='localizacao',
        ),
        migrations.AddField(
            model_name='gerenciadoras',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização: '),
        ),
        migrations.AddField(
            model_name='gerenciadoras',
            name='tagQuadro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag Quadro: '),
        ),
    ]
