# Generated by Django 3.0 on 2020-12-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_auto_20201205_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suc', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeLoja', models.CharField(blank=True, max_length=255, null=True)),
                ('integracaoSdai', models.CharField(choices=[('SIM', 'SIM'), ('SIM', 'SIM')], max_length=255)),
                ('medidorEnergia', models.CharField(choices=[('SIM', 'SIM'), ('SIM', 'SIM')], max_length=255)),
            ],
        ),
    ]
