# Generated by Django 3.0 on 2020-12-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0004_suc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suc',
            options={'verbose_name': 'SUC'},
        ),
        migrations.AlterModelTable(
            name='suc',
            table='tbSuc',
        ),
    ]
