# Generated by Django 3.0 on 2020-12-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0006_auto_20201205_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='statusCamera',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default=1, max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
