# Generated by Django 3.0 on 2020-12-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0007_cameras_statuscamera'),
    ]

    operations = [
        migrations.AddField(
            model_name='sap',
            name='quadroEletrico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quadros Elétrico: '),
        ),
    ]
